const menu = [

    {
        id:1,
        title:"pizza margherita",
        category:"Pizza",
        price:29.99,
        image:"./images/pizzas/pizza-mar.jpg",
        desc:"La pizza Margherita est une spécialité culinaire traditionnelle de la ville de Naples, en Italie. Très populaire",
    },
    {
        id:2,
        title:"Pizza quatre saisons",
        category:"Pizza",
        price:20.99,
        image:"./images/pizzas/pizza-4-saisons.jpg",
        desc:"La pizza quatre saisons est une variété de pizza préparée en quatre portions comportant des ingrédients différents",
    },
    {
        id:3,
        title:"pizza végétarienne",
        category:"Pizza",
        price:30.99,
        image:"./images/pizzas/pizza-veg.jpg",
        desc:"La pizza quatre saisons est une variété de pizza préparée en quatre portions comportant des ingrédients différents",
    },
    {
        id:4,
        title:"Cheeseburger",
        category:"Burger",
        price:21.99,
        image:"./images/burgers/burger-cheese.jpg",
        desc:"Un cheeseburger ou hamburger au fromage est un hamburger dans lequel une tranche de fromage accompagne la viande. ",
    },
    {
        id:5,
        title:"Salade César",
        category:"Salade",
        price:25.99,
        image:"./images/salades/salade-ces.jpg",
        desc:"La salade César est une recette de cuisine de salade composée de la cuisine américaine. ",
    },
    {
        id:6,
        title:"Salade Niçoise",
        category:"Salade",
        price:29.99,
        image:"./images/salades/salade-nic.jpg",
        desc:"La salade niçoise est une spécialité culinaire traditionnelle de la cuisine niçoise.",
    },
    {
        id:7,
        title:"Tajine Kefta",
        category:"Tajine",
        price:40.99,
        image:"./images/tajines/tajine-kefta.jpg",
        desc:"Un tajine ou tagine ou tadjine désigne tout autant un plat de cuisson et de service.",
    },
    {
        id:8,
        title:"Tajine Poisson",
        category:"Tajine",
        price:45.99,
        image:"./images/tajines/tajine-poisson.jpg",
        desc:"Un tajine ou tagine ou tadjine désigne tout autant un plat de cuisson et de service.",
    },
    {
        id:9,
        title:"Tajine Poulet",
        category:"Tajine",
        price:45.99,
        image:"./images/tajines/tajine-poulet.jpg",
        desc:"Un tajine ou tagine ou tadjine désigne tout autant un plat de cuisson et de service.",
    },
    {
        id:10,
        title:"Couscous",
        category:"Traditional",
        price:35.99,
        image:"./images/traditional/couscous.jpg",
        desc:"Le couscous est d'une part une semoule de blé dur préparée à l'huile d'olive et d'autre part.",
    },
    {
        id:11,
        title:"R'fissa",
        category:"Traditional",
        price:38.99,
        image:"./images/traditional/rfissa.jpg",
        desc:"La rfissa est un mets culinaire marocain, à base de msemmen, d'un bouillon d'oignons, de gingembre ...",
    },
    {
        id:12,
        title:"Seffa",
        category:"Traditional",
        price:30.99,
        image:"./images/traditional/seffa.jpg",
        desc:"La seffa, plat marocain et algérien à base de semoule, est un couscous sucré à la cannelle et aux amandes.",
    },
    {
        id:13,
        title:"Taco au poulet",
        category:"Tacos",
        price:15.99,
        image:"./images/tacos/taco-poulet.jpg",
        desc:"4 feuilles de tortillas,4 escalopes de poulet ou de dinde,20 cl de crème liquide,100 g de fromage râpé,1 oignon.",
    },

]

export default menu

